name = "PinCFlow"
uuid = "230a4047-f24c-41d9-8d93-b3b8a5ef3847"
version = "0.1.0"
authors = ["Felix Jochum", "Irmgard Knop", "Jonas Rothermel", "Marco Artiano", "Arpit Babbar", "Hendrik Ranocha", "Stamen Dolaptchiev", "Sandra Klewinghaus", "Ulrich Achatz"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
#Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
#MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
#PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
#Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
#Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
#BenchmarkTools = "1.6.0"
Dates = "1.10.0"
#JuliaFormatter = "1.0.62"
LinearAlgebra = "1.11.0"
#MPICH_jll = "4.3.0"
#PythonPlot = "1.0.6"
Random = "1.11.0"
#Revise = "3.8.0"
Statistics = "1.11.1"
CairoMakie = "0.15.6"
HDF5 = "0.17.2"
MPI = "0.20.23"
#Revise = "3.9.0"
julia = "1.10.10"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
#PinCFlowPythonPlotExt = "PythonPlot"
PinCFlowMakieExt = "CairoMakie"

<<<<<<< HEAD
=======
[compat]
CairoMakie = "0.15.6"
HDF5 = "0.17.2"
JuliaFormatter = "1.0.62"
MPI = "0.20.23"
Revise = "3.9.0"
julia = "1.10.10"

>>>>>>> cf395edbf2
[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuliaFormatter", "LinearAlgebra", "Revise", "Test"]
