name = "PinCFlow"
uuid = "230a4047-f24c-41d9-8d93-b3b8a5ef3847"
authors = ["Felix Jochum", "Irmgard Knop", "Jonas Rothermel", "Marco Artiano", "Arpit Babbar", "Hendrik Ranocha", "Stamen Dolaptchiev", "Sandra Klewinghaus", "Ulrich Achatz"]
version = "1.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
PinCFlowMakieExt = "CairoMakie"

[compat]
CairoMakie = "0.15.6"
HDF5 = "0.17.2"
JuliaFormatter = "1.0.62"
LaTeXStrings = "1.4.0"
MPI = "0.20.23"
Revise = "3.9.0"
julia = "1.10.10"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuliaFormatter", "LinearAlgebra", "Revise", "Test"]
