[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
PinCFlow = "230a4047-f24c-41d9-8d93-b3b8a5ef3847"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
CairoMakie = "0.15.6"
HDF5 = "0.17.2"
HDF5_jll = "1.14.6"
MPI = "0.20.23"
MPICH_jll = "4.3.1"
MPIPreferences = "0.1.11"
PinCFlow = "1.0.0"
Revise = "3.9.0"
julia = "1.10.10"
