name: Draft PDF

on:
  push:
    paths:
      - paper/**
      - .github/workflows/DraftPDF.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate LaTeX source code and compiled PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k paper/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper
